export type Step = {
  icon: string
  label: string
  data: string
  done: boolean
}

export type Prodotto = {
  id: string
  nome: string
  cat: 'ortaggi' | 'legumi' | 'cereali' | 'farine' | 'trasformati' | 'pasta'
  emoji: string
  bio: boolean
  bg: string
  img?: string     // path immagine prodotto (opzionale)
  prezzo: string   // TODO: inserire prezzo reale
  unita: string    // TODO: inserire unità reale (kg, 500g, ecc.)
  desc: string
  lotto: string    // TODO: inserire lotto reale
  raccolta: string // TODO: inserire data raccolta reale
  campo: string    // TODO: inserire campo/località reale
  varieta: string  // TODO: inserire varietà reale
  metodo: string   // TODO: inserire metodo coltivazione reale
  cert: string     // TODO: inserire certificazione reale
  steps: Step[]
}

export const prodotti: Prodotto[] = [

  // ── CEREALI ──
  { id: 'C001', nome: 'Grano Tenero', cat: 'cereali', emoji: '🌾', bio: false, bg: '#fdf6e3', img: '/images/prodotti/grano_tenero.jpg', prezzo: '— TODO —', unita: 'kg', desc: "I cereali disegnano il paesaggio e ne scandiscono il tempo. Dalla semina alla maturazione, accompagnano le stagioni con regolarità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Grano Tenero', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'C002', nome: 'Grano Duro', cat: 'cereali', emoji: '🌾', bio: false, bg: '#fdf6e3', img: '/images/prodotti/grano_duro.jpg', prezzo: '— TODO —', unita: 'kg', desc: "I cereali disegnano il paesaggio e ne scandiscono il tempo. Dalla semina alla maturazione, accompagnano le stagioni con regolarità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Grano Duro', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'C003', nome: 'Grano Solina', cat: 'cereali', emoji: '🌾', bio: false, bg: '#fdf6e3', img: '/images/prodotti/grano_solina.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Varietà antica tipica dell'Appennino abruzzese, coltivata in quota. Dalla semina alla maturazione, accompagna le stagioni con regolarità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Solina', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'C004', nome: 'Grano Senatore Cappelli', cat: 'cereali', emoji: '🌾', bio: false, bg: '#fdf6e3', img: '/images/prodotti/grano_senatore_cappelli.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Varietà storica di grano duro, ricca di proteine e dal profilo nutrizionale eccellente. Materia prima essenziale, solida, profondamente legata al territorio.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Senatore Cappelli', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'C005', nome: 'Orzo', cat: 'cereali', emoji: '🌾', bio: false, bg: '#fdf6e3', img: '/images/prodotti/orzo.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Cereale versatile e nutriente, coltivato nei campi del Fucino. Dalla semina alla maturazione, accompagna le stagioni con regolarità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Orzo', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'C006', nome: 'Mais', cat: 'cereali', emoji: '🌽', bio: false, bg: '#fdf6e3', img: '/images/prodotti/mais.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Mais coltivato nelle fertili pianure del Fucino. Materia prima essenziale, solida, profondamente legata al territorio.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Mais', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'C007', nome: 'Farro', cat: 'cereali', emoji: '🌾', bio: false, bg: '#fdf6e3', img: '/images/prodotti/farro.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Antico cereale ricco di proteine, fibre e minerali. Coltivato in altura, disegna il paesaggio e ne scandisce il tempo.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Farro', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },

  // ── LEGUMI ──
  { id: 'L001', nome: 'Fagioli Borlotti', cat: 'legumi', emoji: '🫘', bio: false, bg: '#fdf2e9', img: '/images/prodotti/fagioli_borlotti.jpg', prezzo: '— TODO —', unita: 'kg', desc: "I legumi rappresentano l'essenza di una cucina semplice e nutriente. Coltivati con attenzione e selezionati dopo la raccolta.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Borlotti', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'L002', nome: 'Fagioli Cannellini', cat: 'legumi', emoji: '🫘', bio: false, bg: '#fdf2e9', img: '/images/prodotti/fagioli_cannellini.jpg', prezzo: '— TODO —', unita: 'kg', desc: "I legumi rappresentano l'essenza di una cucina semplice e nutriente. Conservano intatto il loro carattere, fatto di sostanza e autenticità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Cannellini', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'L003', nome: 'Ceci', cat: 'legumi', emoji: '🫘', bio: false, bg: '#fdf2e9', img: '/images/prodotti/ceci.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Ceci coltivati nelle campagne della Marsica. Conservano intatto il loro carattere, fatto di sostanza e autenticità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Ceci', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'L004', nome: 'Lenticchie', cat: 'legumi', emoji: '🫘', bio: false, bg: '#fdf2e9', img: '/images/prodotti/lenticchie.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Lenticchie della Marsica, piccole e profumate. Coltivate con attenzione e selezionate dopo la raccolta, conservano intatto il loro carattere.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Lenticchie', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'L005', nome: 'Piselli', cat: 'legumi', emoji: '🟢', bio: false, bg: '#fdf2e9', img: '/images/prodotti/piselli.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Piselli freschi coltivati nelle campagne di Pescina. Conservano intatto il loro carattere, fatto di sostanza e autenticità.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Piselli', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Crescita', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },

  // ── FARINE ──
  { id: 'F001', nome: 'Farina di Grano Tenero', cat: 'farine', emoji: '🌾', bio: false, bg: '#fef9e7', img: '/images/prodotti/farina_di_grano_tenero.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Farina derivata da cereali coltivati nei nostri campi e lavorati per mantenere equilibrio e fragranza. Filiera completamente controllata.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Grano Tenero', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌾', label: 'Raccolta cereale', data: 'TODO', done: false },{ icon: '🏭', label: 'Molitura', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '📦', label: 'Confezionamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'F002', nome: 'Farina di Grano Duro', cat: 'farine', emoji: '🌾', bio: false, bg: '#fef9e7', img: '/images/prodotti/farina_di_grano_duro.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Farina di semola da grano duro coltivato nei campi del Fucino. Risultato di una filiera controllata, pensata per chi apprezza materie prime sincere.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Grano Duro', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌾', label: 'Raccolta cereale', data: 'TODO', done: false },{ icon: '🏭', label: 'Molitura', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '📦', label: 'Confezionamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'F003', nome: 'Farina di Ceci', cat: 'farine', emoji: '🟡', bio: false, bg: '#fef9e7', img: '/images/prodotti/farina_di_ceci.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Farina di ceci ottenuta da legumi coltivati in azienda. Filiera completamente controllata, dal campo alla confezione.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Ceci', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🫘', label: 'Raccolta ceci', data: 'TODO', done: false },{ icon: '🏭', label: 'Molitura', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '📦', label: 'Confezionamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'F004', nome: 'Farina di Farro', cat: 'farine', emoji: '🌾', bio: false, bg: '#fef9e7', img: '/images/prodotti/farina_di_farro.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Farina di farro macinata da cereale antico coltivato in azienda. Equilibrio e fragranza, il risultato di una filiera controllata.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Farro', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌾', label: 'Raccolta farro', data: 'TODO', done: false },{ icon: '🏭', label: 'Molitura', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '📦', label: 'Confezionamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },

  // ── ORTAGGI ──
  { id: 'O001', nome: 'Patate', cat: 'ortaggi', emoji: '🥔', bio: false, bg: '#f0f4e8', img: '/images/prodotti/patate.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Patate coltivate nelle campagne di Pescina, nel cuore della Marsica. Terra fertile e autentica dove l'agricoltura segue il ritmo naturale delle stagioni.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O002', nome: 'Carote', cat: 'ortaggi', emoji: '🥕', bio: false, bg: '#f0f4e8', img: '/images/prodotti/carote.webp', prezzo: '— TODO —', unita: 'kg', desc: "Carote coltivate nei campi del Fucino con cura quotidiana e rispetto per la terra, tra campi aperti e aria di montagna.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O003', nome: 'Cipolle', cat: 'ortaggi', emoji: '🧅', bio: false, bg: '#f0f4e8', img: '/images/prodotti/cipolle.webp', prezzo: '— TODO —', unita: 'kg', desc: "Cipolle coltivate nel cuore della Marsica con cura quotidiana e rispetto per la terra.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O004', nome: 'Aglio', cat: 'ortaggi', emoji: '🧄', bio: false, bg: '#f0f4e8', img: '/images/prodotti/aglio.webp', prezzo: '— TODO —', unita: 'kg', desc: "Aglio coltivato nelle campagne di Pescina, nel cuore della Marsica, con rispetto per la terra e le stagioni.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O005', nome: 'Radicchio', cat: 'ortaggi', emoji: '🥬', bio: false, bg: '#f0f4e8', img: '/images/prodotti/radicchio.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Radicchio fresco coltivato nei campi aperti della Marsica, dove l'agricoltura segue ancora il ritmo naturale delle stagioni.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O006', nome: 'Finocchi', cat: 'ortaggi', emoji: '🌿', bio: false, bg: '#f0f4e8', img: '/images/prodotti/finocchi.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Finocchi coltivati con cura quotidiana nel cuore della Marsica, in una terra fertile e autentica.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O007', nome: 'Cavoli', cat: 'ortaggi', emoji: '🥦', bio: false, bg: '#f0f4e8', img: '/images/prodotti/cavoli.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Cavoli coltivati nelle campagne di Pescina, tra campi aperti e aria di montagna, con rispetto per la terra.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Semina', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O008', nome: 'Pomodori', cat: 'ortaggi', emoji: '🍅', bio: false, bg: '#f0f4e8', img: '/images/prodotti/pomodori.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Pomodori coltivati nel cuore della Marsica. Terra fertile e autentica dove l'agricoltura segue il ritmo naturale delle stagioni.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Trapianto', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O009', nome: 'Zucchine', cat: 'ortaggi', emoji: '🥒', bio: false, bg: '#f0f4e8', img: '/images/prodotti/zucchine.webp', prezzo: '— TODO —', unita: 'kg', desc: "Zucchine coltivate nelle campagne di Pescina con cura quotidiana e rispetto per la terra.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Trapianto', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'O010', nome: 'Melanzane', cat: 'ortaggi', emoji: '🍆', bio: false, bg: '#f0f4e8', img: '/images/prodotti/melanzane.jpg', prezzo: '— TODO —', unita: 'kg', desc: "Melanzane coltivate nel cuore della Marsica, tra campi aperti e aria di montagna.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌱', label: 'Trapianto', data: 'TODO', done: false },{ icon: '🌿', label: 'Coltivazione', data: 'TODO', done: false },{ icon: '🚜', label: 'Raccolta', data: 'TODO', done: false },{ icon: '🏭', label: 'Selezione', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },

  // ── TRASFORMATI ──
  { id: 'T001', nome: 'Passata di Pomodoro', cat: 'trasformati', emoji: '🍅', bio: false, bg: '#fde8e8', prezzo: '— TODO —', unita: 'vasetto', desc: "Passata ottenuta da pomodori coltivati in azienda. Lavorazioni semplici che rispettano l'identità dell'origine, capaci di custodire il valore del raccolto.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🍅', label: 'Raccolta pomodori', data: 'TODO', done: false },{ icon: '🏭', label: 'Lavorazione', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '🫙', label: 'Invasettamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'T002', nome: 'Aglio Marinato', cat: 'trasformati', emoji: '🧄', bio: false, bg: '#fde8e8', prezzo: '— TODO —', unita: 'vasetto', desc: "Aglio marinato con lavorazioni semplici che rispettano l'identità dell'origine. Prodotto pensato per durare, senza artifici.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🧄', label: 'Raccolta aglio', data: 'TODO', done: false },{ icon: '🏭', label: 'Preparazione', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '🫙', label: 'Invasettamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'T003', nome: 'Aglio in Polvere', cat: 'trasformati', emoji: '🧄', bio: false, bg: '#fde8e8', prezzo: '— TODO —', unita: 'confezione', desc: "Aglio in polvere ottenuto da aglio coltivato in azienda. Capace di custodire il valore del raccolto e di raccontare la terra da cui proviene.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🧄', label: 'Raccolta aglio', data: 'TODO', done: false },{ icon: '🏭', label: 'Essiccazione', data: 'TODO', done: false },{ icon: '⚙️', label: 'Macinazione', data: 'TODO', done: false },{ icon: '📦', label: 'Confezionamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'T004', nome: 'Sottaceti', cat: 'trasformati', emoji: '🥒', bio: false, bg: '#fde8e8', prezzo: '— TODO —', unita: 'vasetto', desc: "Verdure sottaceto preparate con lavorazioni semplici che rispettano l'identità dell'origine, pensate per durare nel tempo.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🥦', label: 'Raccolta verdure', data: 'TODO', done: false },{ icon: '🏭', label: 'Preparazione', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '🫙', label: 'Invasettamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },
  { id: 'T005', nome: "Sott'oli", cat: 'trasformati', emoji: '🫙', bio: false, bg: '#fde8e8', prezzo: '— TODO —', unita: 'vasetto', desc: "Verdure sott'olio preparate con lavorazioni semplici, senza artifici. Capaci di custodire il valore del raccolto.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'TODO-VARIETA', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🥦', label: 'Raccolta verdure', data: 'TODO', done: false },{ icon: '🏭', label: 'Preparazione', data: 'TODO', done: false },{ icon: '🔬', label: 'Controllo qualità', data: 'TODO', done: false },{ icon: '🫙', label: 'Invasettamento', data: 'TODO', done: false },{ icon: '🛒', label: 'Distribuzione', data: 'TODO', done: false }] },

  // ── PASTA ──
  { id: 'PA001', nome: 'Pasta Senatore Cappelli', cat: 'pasta', emoji: '🍝', bio: false, bg: '#fdf6e3', prezzo: '— TODO —', unita: '500g', desc: "Pasta di semola di grano duro Senatore Cappelli, varietà storica coltivata in azienda. Filiera completamente controllata dal campo alla confezione.", lotto: 'TODO-LOTTO', raccolta: 'TODO-DATA', campo: 'TODO-CAMPO', varieta: 'Senatore Cappelli', metodo: 'TODO-METODO', cert: 'TODO-CERT', steps: [{ icon: '🌾', label: 'Raccolta grano', data: 'TODO', done: false },{ icon: '🏭', label: 'Molitura semola', data: 'TODO', done: false },{ icon: '⚙️', label: 'Trafilatura', data: 'TODO', done: false },{ icon: '🌬️', label: 'Essiccazione lenta', data: 'TODO', done: false },{ icon: '📦', label: 'Confezionamento', data: 'TODO', done: false }] },
]

export const nomeCat = (cat: string) =>
  ({ ortaggi: 'Ortaggio', legumi: 'Legume', cereali: 'Cereale', farine: 'Farina', trasformati: 'Trasformato', pasta: 'Pasta' }[cat] ?? cat)
